<?php
$client_id = "978342e86e454e4f8158c9cc2dc58458";
$secret = "c8f23a6494f84d7b9b5f3b747bd3e988";
$scope = "playlist-read-collaborative playlist-modify-public playlist-read-private playlist-modify-private";
$redirect_uri = "http://localhost:8080/index/spotify";
$url = "https://accounts.spotify.com/authorize?response_type=code&client_id=$client_id&scope=$scope&redirect_uri=$redirect_uri";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotify</title>
    <link rel="icon" type="image/gif/png" href="https://cdn-icons-png.flaticon.com/512/174/174872.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-image: url('https://wallpaperaccess.com/full/16692.jpg');
            background-repeat: no-repeat;
            background-size: inherit;
            overflow: hidden;
        }
        .login:hover{
            background-color: transparent;
        }
    </style>
</head>

<body>
    <div>
        
        <a href="<?php echo $url; ?>" class="btn btn-dark login" style="border-radius: 50px; width:20%; margin-top: 25%; float:right; margin-right:10%;padding: 20px;"><img src="https://cdn-icons-png.flaticon.com/512/174/174872.png" alt="spotify" style="height: 25px; width:25px;">&nbsp&nbspLogin With Spotify</a>
    </div>
</body>

</html>