<?php
$a = '';
foreach ($playlist['items'] as $k => $v) {
    $a .= '<option value=' . $v['id'] . '>' . $v['name'] . '</option>';
}
// die;
?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <title>Spotify</title>
    <link rel="icon" type="image/gif/png" href="https://cdn-icons-png.flaticon.com/512/174/174872.png">
</head>
<style>
    @media (min-width: 1025px) {
        .h-custom {
            height: 100vh !important;
        }
    }

    body {
        background-image: url('https://media.istockphoto.com/photos/cement-floor-and-black-wall-backgrounds-empty-room-interior-use-for-picture-id1226232663?k=20&m=1226232663&s=612x612&w=0&h=vIjeJxN1qRTIyjUNJOzOsH3hgmHU04bZsi7WV4qUCxY=');
        background-repeat: no-repeat;
        background-size: cover;
        /* overflow: hidden; */
        color: white;
    }

    .typewriter {
        color: #fff;
        font-family: 'Times New Roman', Times, serif;
        overflow: hidden;
        /* Ensures the content is not revealed until the animation */
        border-right: .15em solid orange;
        /* The typwriter cursor */
        white-space: nowrap;
        /* Keeps the content on a single line */
        margin: 0 auto;
        /* Gives that scrolling effect as the typing happens */
        letter-spacing: .15em;
        /* Adjust as needed */
        animation:
            typing 3.5s steps(30, end),
            blink-caret .5s step-end infinite;
    }

    /* The typing effect */
    @keyframes typing {
        from {
            width: 0
        }

        to {
            width: 210%
        }
    }

    /* The typewriter cursor effect */
    @keyframes blink-caret {

        from,
        to {
            border-color: transparent
        }

        200% {
            border-color: orange
        }
    }
</style>

</style>

<body>
    <section class="mt-5" style="overflow: hidden;">

        <div class="container h-50">
            <div class="row">
                <label>Create Playlist</label>
                <div class="col">
                    <form class="px-md-2" method="POST" action="/index/createPlaylist">
                        <input name="playlist" type="text" class="" id="floatingInput" placeholder="Playlist">

                        <input name="description" type="text" class="" id="floatingInput" placeholder="Description">
                        <input name="create" type="submit" class="btn btn-danger" id="floatingInput" placeholder="Description">
                        <?php if ($this->session->get('msg')) {
                            echo $msg;
                        }
                        ?>
                    </form>
                </div>
            </div>

            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-8 col-xl-10">

                    <h3 class="typewriter">Search Your favourite Album, Genre, Artists...</h3>

                    <form class="px-md-2" method="POST" action="/index/search">
                        <div class="form-floating mb-3">
                            <input name="q" type="text" class="form-control" id="floatingInput" placeholder="Search" style="border-radius: 100px; text-align:center; display:inline">
                            <label for="floatingPassword" class="text-muted">Artists, songs, or Podcasts</label>

                        </div>


                        <span>Filters:
                            <input type="checkbox" name='type[]' value="albums"> Album
                            <input type="checkbox" name='type[]' value="artists"> Artists
                            <input type="checkbox" name='type[]' value="playlists"> PlayLists
                            <input type="checkbox" name='type[]' value="tracks"> Tracks
                            <input type="checkbox" name='type[]' value="shows"> Shows
                            <input type="checkbox" name='type[]' value="episodes"> Episodes
                        </span><br>


                        <input type="submit" value="Search" name="search" class="btn btn-success" style="border-radius: 100px; text-align:center; float:left">
                </div>
                </form>

                <?php echo $count; ?>
            </div>
        </div>
        <?php

        // if ($count) {
        //     echo $count . '' . $title . '' . implode($author_name) . '' . $FPY;
        // }
        if ($NRF) {
            echo $NRF;
        }

        ?>
    </section>
    <?php
    error_reporting(0);
    // die($count);
    if ($response) {
        $html = '';
        // die('hey');
        foreach ($response as $key => $value) {
            foreach ($value['items'] as $f => $s) {
                $html .= '<div class="card" style="display:inline; margin-left:1%; margin-top: 1%; float:left">
        <div class="col">
        <div class="card-img-top bg-dark text-light" style="width: 25rem;">
        <img src=' . $s['album']['images'][1]['url'] . ' class="card-img-top" alt="img" height="350">
        <div class="card-body ">
        <p class="card-title">' . $s['album']['name'] . '</p>
        <p class="card-title">' . $s['album']['release_date'] . '</p>
          <p class="card-title text-muted">by ' . $s['album']['artists'][0]['name'] . '</p>
          <form method="post" action="/index/search">
          <input type="hidden" name="uri" value=' . $s['uri'] . '>
          <select id="playlist" name="playlist" class="btn btn-primary">
          <option>Add To Playlist</option>
          ' . $a . '
          </select>
          <input type="submit" name="addtoplaylist" class="btn btn-outline-success" style="width:auto; height:auto;" value="Submit"/>
          </form>        </div>
      </div>
      </div>
      </div>';
            }
        }

        echo $html;
    }

    if ($response_Album) {
        echo '<h3>Albums</h3>';
        $html = '';
        foreach ($response_Album as $key => $value) {
            foreach ($value['items'] as $f => $s) {

                $html .= '<div class="row" style="display:inline; margin-left:1%; margin-top: 1%; float:left">
        <div class="col col-2">
        <div class="card bg-dark text-light" style="width: 25rem;">
        <img src=' . $s['images'][1]['url'] . ' class="card-img-top" alt="img" height="350">
        <div class="card-body ">
        <p class="card-title">' . $s['name'] . '</p>
        <p class="card-title">' . $s['release_date'] . '</p>
          <p class="card-title text-muted">by ' . $s['artists'][0]['name'] . '</p>
         
        </div>
      </div>
      </div>
      </div>';
            }
        }
        echo $html;
    }

    if ($response_Artist) {
        echo '<h3>Artists</h3><br>';
        $html = '';
        foreach ($response_Artist as $key => $value) {
            foreach ($value['items'] as $f => $s) {

                $html .= '<div class="row" style="display:inline; margin-left:1%; margin-top: 1%; float:left">
        <div class="col col-2">
        <div class="card bg-dark text-light" style="width: 25rem;">
        <img src=' . $s['images'][0]['url'] . ' class="card-img-top" alt="img" height="350">
        <div class="card-body ">
        <p class="card-title">' . $s['name'] . '</p>
          <p class="card-title text-muted">Artist</p>
          
        </div>
      </div>
      </div>
      </div>';
            }
        }
        echo $html;
    }

    if ($response_Playlist) {
        echo '<h3>PlayLists</h3><br>';
        $html = '';
        foreach ($response_Playlist as $key => $value) {
            foreach ($value['items'] as $f => $s) {

                $html .= '<div class="row" style="display:inline; margin-left:1%; margin-top: 1%; float:left">
        <div class="col col-2">
        <div class="card bg-dark text-light" style="width: 25rem;">
        <img src=' . $s['images'][0]['url'] . ' class="card-img-top" alt="img" height="350">
        <div class="card-body ">
        <p class="card-title">' . $s['name'] . '</p>
          <p class="card-title text-muted">by ' . $s['owner']['display_name'] . '</p>
          
        </div>
      </div>
      </div>
      </div>';
            }
        }
        echo $html;
    }
    if ($response_Track) {
        echo '<h3>Tracks</h3><br>';
        $html = '';
        foreach ($response_Track as $key => $value) {
            foreach ($value['items'] as $f => $s) {

                $html .= '<div class="row" style="display:inline; margin-left:1%; margin-top: 1%; float:left">
        <div class="col col-2">
        <div class="card bg-dark text-light" style="width: 25rem;">
        <img src=' . $s['album']['images'][1]['url'] . ' class="card-img-top" alt="img" height="350">
        <div class="card-body ">
        <p class="card-title">' . $s['album']['name'] . '</p>
        <p class="card-title">' . $s['album']['release_date'] . '</p>
          <p class="card-title text-muted">by ' . $s['album']['artists'][0]['name'] . '</p>
          <form method="post" action="">
          <input type="submit" class="btn btn-primary" style="width:auto; height:auto;" value="Add To Playlist"/>
          </form>
        </div>
      </div>
      </div>
      </div>';
            }
        }
        echo $html;
    }
    if ($response_Episodes) {
        echo '<h3>Episodes</h3><br>';
        $html = '';
        foreach ($response_Episodes as $key => $value) {
            foreach ($value['items'] as $f => $s) {

                $html .= '<div class="row" style="display:inline; margin-left:1%; margin-top: 1%; float:left">
        <div class="col col-2">
        <div class="card bg-dark text-light" style="width: 25rem;">
        <img src=' . $s['images'][0]['url'] . ' class="card-img-top" alt="img" height="350">
        <div class="card-body ">
        <p class="card-title">' . $s['name'] . '</p>
        </div>
      </div>
      </div>
      </div>';
            }
        }
        echo $html;
    }


    ?>





</body>

</html>